apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datacenter-service
  labels:
    app: {{ .Release.Name }}-datacenter-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: {{ .Release.Name }}-datacenter-service
  type: ClusterIP