
spring:
  data:
    mongodb:
      host: localhost
      database: datacenter
  rabbitmq:
    host: rabbitmq.svc
    port: 5672
plus:
  datacenter:
    amqp:
      exchange: datacenter-test
      sync:
        enabled: true
