client:
  id: "test"
  secret: "e6423085f5165a58f8949e763c6691ffe44e2f86"
  apiEndpoint: "https://api.dustlight.cn"
  tokenUri: "https://api.dustlight.cn/v1/oauth/token"
  checkTokenUri: "https://api.dustlight.cn/v1/token/validity"
  jwkSetUri: "https://api.dustlight.cn/v1/jwk"

dustlight:
  auth:
    oauth2:
      client:
        client-id: ${client.id}
        client-secret: ${client.secret}
        api-endpoint: ${client.apiEndpoint}
        token-uri: ${client.tokenUri}
      resource-server:
        client-id: ${client.id}
        client-secret: ${client.secret}
        uri: ${client.checkTokenUri}
        jwk-set-uri: ${client.jwkSetUri}
  datacenter:
    form:
      schema-additional:
        - key: $id
          value: ${dustlight.datacenter.schema.parameters.endpoint}/${dustlight.datacenter.schema.parameters.prefix}/
        - key: $schema
          value: ${dustlight.datacenter.schema.parameters.endpoint}/${dustlight.datacenter.schema.parameters.prefix}${dustlight.datacenter.schema.adapter.form-schema}
    authorization-endpoint: "https://accounts.dustlight.cn/authorize"
    mongo:
      form-collection: form
      record-collection: form_record
    amqp:
      exchange: datacenter
      sync:
        enabled: true
        queue: datacenter-sync
        dead-letter-queue: datacenter-sync-dead
    schema:
      parameters:
        prefix: v1/schemas
        endpoint: http://localhost:8080
      mapping: /${dustlight.datacenter.schema.parameters.prefix}/**
      adapter:
        meta-schema: /schema
        form-schema: /form
        non-validation-keywords:
          - form
    elasticsearch:
      record-prefix: datacenter.form_record
      form-prefix: datacenter.form
# SpringDoc 配置
springdoc:
  api-docs:
    enabled: on
    path: /doc
  swagger-ui:
    path: /doc.html
    oauth:
      client-id: ${client.id}
      additional-query-string-params:
        jwt: true
spring:
  data:
    mongodb:
      uri: mongodb://my-user:MTIzNDU2@localhost:27017/datacenter?authSource=admin&appname=datacenter&directConnection=true
    elasticsearch:
      client:
        reactive:
          endpoints:
            - localhost:9200
  rabbitmq:
    addresses: localhost
    port: 5672
    username: datacenter
    password: datacenter
logging:
  level:
    cn.dustlight.datacenter.*: debug
