replicaCount: 1

image:
  repository: dustlightcn/datacenter-service
  tag: "0.0.6-alpha-3"

ingress:
  className: "nginx"
  host: "datacenter.dustlight.cn"
  tls:
    enabled: false
    crt: ""
    key: ""

monstache:
  replicaCount: 1
  image: "rwynn/monstache:latest"

config:
  elasticsearch:
    endpoints:
      - "elasticsearch-master:9200"
  mongodb:
    uri: ""
    database: "datacenter"
  rabbitmq:
    host: "rabbitmq-svc"
    port: 5672
    username: ""
    password: ""
  auth:
    clientId: "test"
    clientSecret: "e6423085f5165a58f8949e763c6691ffe44e2f86"
    apiEndpoint: "https://api.dustlight.cn"
    tokenUri: "https://api.dustlight.cn/v1/oauth/token"
    checkTokenUri: "https://api.dustlight.cn/v1/token/validity"
    jwkSetUri: "https://api.dustlight.cn/v1/jwk"
    authorizationEndpoint: "https://accounts.dustlight.cn/authorize"

logging: debug