#spring:
#  data:
#    mongodb:
#      host: localhost
#      database: datacenter

spring:
  data:
    mongodb:
      host: mongodb.svc
      username: my-user
      password: MTIzNDU2
      authentication-database: admin
      database: datacenter

